services:
  java:
    image: mcr.microsoft.com/devcontainers/java:dev-17-jdk-bookworm
    volumes:
      - ./:/workspace
    entrypoint: "tail -f /dev/null"
  docmake:
    image: ghcr.io/langchr86/docmake@sha256:32d37fb9a637f0bd2b7860305a31e29ceb665f5f8f884b463a1da4d74cbf308d
    volumes:
      - ./:/workspace
  systemd:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-scs}/systemd-image:1
    build:
      context: .devcontainer/systemd
    volumes:
      - ./:/workspace
