services:
  systemd:
    image:  ${REGISTRY:-ghcr.io}/${REPO_OWNER:-scs}/fedora-systemd:${VERSION:-latest}
    build: container
    volumes:
      - ./hello_world_service:/hello_world_service/hello_world_service
      - ./solution:/hello_world_service/solution
    privileged: true
