name: CMake exercise

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure and build
        working-directory: topics/build_systems/code
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build

      - name: run tests
        working-directory: topics/build_systems/code
        run: |
          cmake --build build --target test
