name: Docker exercise

on:
  - push
  - pull_request

jobs:
  docker-exercise:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: build docker image
        working-directory: topics/docker/code/hostcontrold-solution
        run: |
          docker build .
